apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-cd-k8s-agent-config
  namespace: unified-cd
data:
  k8s-agent-config.yaml: |
    server: "CHANGEME"
    enrollmentPolicy: unified-cd-k8s-agents
    serviceAccountTokenFile: /var/run/secrets/unified-cd-agent/token
    labels:
      - kind:kubernetes
    namespace: ci
    maxConcurrent: 5
    podImage: golang:1.24-alpine
