apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-cd-controller-config
  namespace: unified-cd
data:
  controller-config.yaml: |
    agentAuth:
      kubernetesClusters:
        - name: in-cluster
      kubernetesEnrollmentPolicies:
        - name: unified-cd-k8s-agents
          cluster: in-cluster
          namespaces: [unified-cd]
          serviceAccounts: [unified-cd-k8s-agent]
          allowedLabels: [kind:kubernetes]
          requiredLabels: [kind:kubernetes]
          capabilities: [pod, container]
          accessTokenTTL: 1h
          enabled: true
