apiVersion: v1
kind: Secret
metadata:
  name: unified-cd-controller
  namespace: unified-cd
type: Opaque
stringData:
  UNIFIED_DB_DSN: "CHANGEME"
  UNIFIED_TOKEN: "CHANGEME"
  UNIFIED_CONTROLLER_KEY: "CHANGEME"
  UNIFIED_S3_ENDPOINT: "CHANGEME"
  UNIFIED_S3_BUCKET: "CHANGEME"
  UNIFIED_S3_KEY: "CHANGEME"
  UNIFIED_S3_SECRET: "CHANGEME"
