apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-cd-k8s-agent-config
  namespace: unified-cd
data:
  k8s-agent-config.yaml: |
    server: http://unified-cd-controller.unified-cd.svc.cluster.local
    agentId: k8s-agent-1
    labels:
      - kind:k8s
    namespace: ci
    maxConcurrent: 5
    podImage: golang:1.24-alpine
---
apiVersion: v1
kind: Secret
metadata:
  name: unified-cd-k8s-agent-secret
  namespace: unified-cd
stringData:
  k8s-agent-secret.yaml: |
    token: "dev-token-change-me"
