apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-cd-k8s-agent
  namespace: unified-cd
  labels:
    app: unified-cd-k8s-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unified-cd-k8s-agent
  template:
    metadata:
      labels:
        app: unified-cd-k8s-agent
    spec:
      serviceAccountName: unified-cd-k8s-agent
      containers:
        - name: k8s-agent
          image: ghcr.io/eirueimi/unified-cd-k8s-agent:latest
          env:
            - name: UNIFIED_K8S_CONFIG
              value: /etc/unified-cd/config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/unified-cd/config.yaml
              subPath: k8s-agent-config.yaml
              readOnly: true
            - name: enrollment-identity
              mountPath: /var/run/secrets/unified-cd-agent
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: unified-cd-k8s-agent-config
        - name: enrollment-identity
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  audience: unified-cd-agent-enrollment
                  expirationSeconds: 3600
